apply plugin: 'com.android.library'

android {
    namespace 'com.kira.learning.rxpermission'
    compileSdk rootProject.ext.version.compileSdk

    defaultConfig {
        minSdkVersion rootProject.ext.version.minSdk
        targetSdkVersion rootProject.ext.version.targetSdk

        consumerProguardFiles "proguard-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions.unitTests.includeAndroidResources = true
    testOptions.unitTests.all {
        // unitTests.returnDefaultValues = true
        // Always show the result of every unit test, even if it passes.
        testLogging {
            events 'passed', 'skipped', 'failed', 'standardOut', 'standardError'
        }
    }
}

dependencies {

    implementation rootProject.ext.android.appcompat
    implementation rootProject.ext.android.fragment
    implementation rootProject.ext.android.annotation

    implementation rootProject.ext.rxjava.rxandroid
    implementation rootProject.ext.rxjava.rxjava
}

// Commented to use JitPack instead of bintray
//apply from: 'install.gradle'
//apply from: 'bintray.gradle'
