plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'com.chaquo.python'// version '15.0.1'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}
android {
    namespace 'com.kira.learning'
    compileSdk rootProject.ext.version.compileSdk
    defaultConfig {
        applicationId rootProject.ext.pkgName

        minSdk rootProject.ext.version.minSdk
        targetSdk rootProject.ext.version.targetSdk

        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true

//        resConfigs 'en' // 资源配置限制
        versionCode 1
        versionName "0.0.1"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }

        manifestPlaceholders = [pkgName: "${rootProject.ext.pkgName}"]

        setProperty("archivesBaseName", "Kira learning_v${versionName}_${time()}")

//        android.applicationVariants.all { variant ->
//            variant.outputs.all {
//                println("variant = $variant")
//                outputFileName = "FinanzasExtremas_v${variant.versionName}_${variant.buildType.name}_${time()}.apk"
//            }
//        }
        python {
            buildPython "python3"  // 自动检测系统Python3
            pip {
                install "numpy"
                install "colorama"
            }
        }
    }

    packagingOptions {
        exclude("*/kotlin/**")
        exclude("META-INF/DEPENDENCIES")
        exclude("META-INF/NOTICE")
        exclude("META-INF/LICENSE")
        exclude("META-INF/LICENSE.txt")
        exclude("META-INF/NOTICE.txt")
        exclude("META-INF/*.version")
    }
    // 显示资源冲突
    aaptOptions.cruncherEnabled = false

    buildFeatures {
        viewBinding = true
        compose true
        buildConfig true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = rootProject.ext.version.compose
    }
    signingConfigs {
        release {
            storeFile file("keystore/kiraapac.jks")
            storePassword "kiraapac2025"
            keyAlias "kiraapac"
            keyPassword "kiraapac2025"
        }
        debug {
            storeFile file("keystore/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }


    buildTypes {
        release {
            buildConfigField "String", "BASE_URL", "${rootProject.ext.release.apiHost}"
            buildConfigField "String", "H5_URL", "${rootProject.ext.release.h5Host}"
            buildConfigField "String", "DATA_URL", "${rootProject.ext.release.bigDataHost}"
            buildConfigField "String", "APP_SECRET", "${rootProject.ext.release.apiSecret}"
            buildConfigField "boolean", "APP_DEBUG", "false"
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            buildConfigField "String", "BASE_URL", "${rootProject.ext.debug.apiHost}"
            buildConfigField "String", "H5_URL", "${rootProject.ext.debug.h5Host}"
            buildConfigField "String", "DATA_URL", "${rootProject.ext.debug.bigDataHost}"
            buildConfigField "String", "APP_SECRET", "${rootProject.ext.debug.apiSecret}"
            buildConfigField "boolean", "APP_DEBUG", "true"
            minifyEnabled false
            signingConfig signingConfigs.debug
            debuggable true
            versionNameSuffix ".alpha"
        }
    }

    kapt {
        correctErrorTypes = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    lintOptions {
        abortOnError false
    }
    sourceSets {
        main {
            jniLibs.srcDirs += ['libs']
        }
    }
    gradle.taskGraph.whenReady {
        tasks.each { task ->
            if (task.name.contains("uploadCrashlyticsMappingFileRelease")) {
                task.enabled = false
            }
        }
    }
}

def time() {
    return new Date().format("MMddyyyyHHmm")
}

dependencies {
    // 本地库依赖
    //    implementation project(path: ':sdks:cache')
    // 权限
    //    implementation project(path: ':rxpermission')
    implementation project(path: ":common")
    implementation project(path: ":camera")
    implementation project(path: ':sdks:bigdata')
    implementation project(path: ':sdks:util')
    implementation project(path: ':stedit')
    implementation project(path: ':player')
    implementation project(path: ':window')
    implementation project(path: ':image')
    implementation project(path: ':richtext')
    implementation project(path: ':codeview')

    // hilt
    implementation rootProject.ext.hilt.hilt_android
    kapt rootProject.ext.hilt.hilt_compiler_android

    //firebase core
    implementation platform(rootProject.ext.firebase.bom)
    implementation rootProject.ext.firebase.analytics
    implementation rootProject.ext.firebase.crashlytics
    implementation rootProject.ext.firebase.messaging

    // room
    implementation rootProject.ext.room.room_runtime
    implementation rootProject.ext.room.room_ktx
    kapt rootProject.ext.room.room_compiler

    // 图片元数据处理
    implementation rootProject.ext.exifinterface.exifinterface
    // 图像裁剪
    implementation rootProject.ext.image.cropper
    //OCR
    implementation rootProject.ext.ocr.mlkit_text_recognition
//    implementation rootProject.ext.ocr.tesseract
//    implementation rootProject.ext.ocr.play_services_vision
//    implementation rootProject.ext.ocr.chinese

    // 文字识别
//    implementation rootProject.ext.other.tesseract
    // 核心库（仅用于 Debug 构建）
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'

//    implementation project(path: ":analysis")
//    implementation rootProject.ext.firebase.messaging
//    implementation rootProject.ext.firebase.firebase_perf
//    implementation rootProject.ext.google.play_services_gcm

}