plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'com.chaquo.python'// version '15.0.1'
//    id 'com.google.gms.google-services'
//    id 'com.google.firebase.crashlytics'
}
android {
    namespace 'com.kira.learning'
    compileSdk rootProject.ext.version.compileSdk
    defaultConfig {
        applicationId rootProject.ext.pkgName

        minSdk rootProject.ext.version.minSdk
        targetSdk rootProject.ext.version.targetSdk

        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true

//        resConfigs 'id' // 资源配置限制
        versionCode 8
        versionName "1.0.5"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }

        manifestPlaceholders = [pkgName: "${rootProject.ext.pkgName}"]

        setProperty("archivesBaseName", "FinanzasExtremas_v${versionName}_${time()}")

//        android.applicationVariants.all { variant ->
//            variant.outputs.all {
//                println("variant = $variant")
//                outputFileName = "FinanzasExtremas_v${variant.versionName}_${variant.buildType.name}_${time()}.apk"
//            }
//        }
        python {
            buildPython "python3"  // 自动检测系统Python3
            pip {
                install "numpy"
                install "colorama"
            }
        }
    }

    packagingOptions {
        exclude("*/kotlin/**")
        exclude("META-INF/DEPENDENCIES")
        exclude("META-INF/NOTICE")
        exclude("META-INF/LICENSE")
        exclude("META-INF/LICENSE.txt")
        exclude("META-INF/NOTICE.txt")
        exclude("META-INF/*.version")
    }
    // 显示资源冲突
    aaptOptions.cruncherEnabled = false

    buildFeatures {
        viewBinding = true
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion rootProject.ext.version.compose
    }
    signingConfigs {
        release {
            storeFile file("keystore/finanzans.jks")
            storePassword "finanzas2023"
            keyAlias "finanzas"
            keyPassword "finanzas2023"
        }
        debug {
            storeFile file("keystore/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }


    buildTypes {
        release {
            buildConfigField "String", "BASE_URL", "${rootProject.ext.release.apiHost}"
            buildConfigField "String", "H5_URL", "${rootProject.ext.release.h5Host}"
            buildConfigField "String", "DATA_URL", "${rootProject.ext.release.bigDataHost}"
            buildConfigField "String", "APP_SECRET", "${rootProject.ext.release.apiSecret}"
            buildConfigField "boolean", "APP_DEBUG", "false"
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            buildConfigField "String", "BASE_URL", "${rootProject.ext.debug.apiHost}"
            buildConfigField "String", "H5_URL", "${rootProject.ext.debug.h5Host}"
            buildConfigField "String", "DATA_URL", "${rootProject.ext.debug.bigDataHost}"
            buildConfigField "String", "APP_SECRET", "${rootProject.ext.debug.apiSecret}"
            buildConfigField "boolean", "APP_DEBUG", "true"
            minifyEnabled false
            signingConfig signingConfigs.debug
            debuggable true
            versionNameSuffix ".alpha"
        }
    }

    kapt {
        correctErrorTypes = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    lintOptions {
        abortOnError false
    }
    sourceSets {
        main {
            jniLibs.srcDirs += ['libs']
        }
    }
}

def time() {
    return new Date().format("yyyyMMddHHmm")
}

dependencies {
    // 本地库依赖
    //    implementation project(path: ':sdks:cache')
    implementation project(path: ":common")
    implementation project(path: ":camera")
    implementation project(path: ':sdks:bigdata')
    implementation project(path: ':sdks:util')
    implementation project(path: ':datepicker')
    implementation project(path: ':stedit')

    // base
    implementation rootProject.ext.android.kotlin_stdlib
    implementation rootProject.ext.android.core_ktx
    implementation rootProject.ext.android.appcompat
    implementation rootProject.ext.view.constraintlayout
    implementation rootProject.ext.view.material
    implementation rootProject.ext.android.multidex
    implementation rootProject.ext.view.swiperefreshlayout
    // livedata
    implementation rootProject.ext.android.lifecycle_runtime
    implementation rootProject.ext.android.lifecycle_livedataKtx
    implementation rootProject.ext.android.livedata_viewmodelKtx

    // hilt
    implementation rootProject.ext.hilt.hilt_android
    kapt rootProject.ext.hilt.hilt_compiler_android

    // 本地maven
    implementation rootProject.ext.other.aes
    implementation rootProject.ext.other.cache
    debugImplementation rootProject.ext.other.devoptions
    // 权限
    implementation project(path: ':rxpermission')
//    implementation rootProject.ext.permission.rxpermission

    // rxjava3.0
    implementation rootProject.ext.rxjava.rxandroid
    implementation rootProject.ext.rxjava.rxjava

    // CameraX 拍照识别图片
    implementation rootProject.ext.camera.core
    implementation rootProject.ext.camera.camera2
    implementation rootProject.ext.camera.lifecycle
    implementation rootProject.ext.camera.view

    //compose 同时支持xml和compose 自定义需求高的用xml
    implementation rootProject.ext.compose.compose_ui
    implementation rootProject.ext.compose.compose_material
    implementation rootProject.ext.compose.compose_runtime
    implementation rootProject.ext.compose.compose_activity
    debugImplementation rootProject.ext.compose.compose_uitooling

    //markwon AI对话专用
    implementation rootProject.ext.markwon.core
    implementation rootProject.ext.markwon.image
    implementation rootProject.ext.markwon.image_glide

    // room
    implementation rootProject.ext.room.room_runtime
    implementation rootProject.ext.room.room_ktx
    kapt rootProject.ext.room.room_compiler

    implementation rootProject.ext.exifinterface.exifinterface
    // 图像裁剪
    implementation 'com.edmodo:cropper:1.0.1'
    // 文字识别
    implementation 'cz.adaptech.tesseract4android:tesseract4android:4.4.0'

    // google分析
    implementation platform('com.google.firebase:firebase-bom:31.5.0')
    implementation 'com.google.firebase:firebase-analytics'

    implementation "androidx.activity:activity-ktx:1.7.0"
    implementation "com.alibaba:fastjson:1.2.76"

}