plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.hjq.window'
    compileSdk rootProject.ext.version.compileSdk

    defaultConfig {
        minSdk rootProject.ext.version.minSdk
        targetSdk rootProject.ext.version.targetSdk

        consumerProguardFiles "proguard-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation rootProject.ext.view.material
    implementation rootProject.ext.android.core_ktx
    implementation rootProject.ext.android.appcompat
}
