plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
}

android {
    namespace 'com.common.lib'
    compileSdk rootProject.ext.version.compileSdk

    defaultConfig {
        minSdkVersion rootProject.ext.version.minSdk
        targetSdkVersion rootProject.ext.version.targetSdk

        consumerProguardFiles "proguard-rules.pro"
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
    
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    composeOptions {
        kotlinCompilerExtensionVersion = rootProject.ext.version.compose
    }
}

dependencies {

    api project(path: ':sdks:util')

    api rootProject.ext.android.kotlin_stdlib
    api rootProject.ext.android.core_ktx
    api rootProject.ext.android.appcompat
    api rootProject.ext.view.constraintlayout
    api rootProject.ext.android.coroutines_android

    api rootProject.ext.view.svg
    api rootProject.ext.view.gif

    implementation rootProject.ext.view.recyclerview

    // hilt
    api rootProject.ext.hilt.hilt_android
    kapt rootProject.ext.hilt.hilt_compiler_android

    //rxjava3.0
    implementation rootProject.ext.rxjava.rxandroid

    api rootProject.ext.android.lifecycle_runtime
    api rootProject.ext.android.lifecycle_livedataKtx
    api rootProject.ext.android.livedata_viewmodelKtx

    //retrofit2.0
    api rootProject.ext.retrofit.retrofit
    api rootProject.ext.retrofit.converter_gson
    api rootProject.ext.retrofit.adapter_rxjava3
    api rootProject.ext.retrofit.gson
    api rootProject.ext.retrofit.logging_interceptor
    api rootProject.ext.retrofit.okhttp
    api rootProject.ext.retrofit.conscrypt

    //glide
    api rootProject.ext.glide.glide

    // 适配
//    api rootProject.ext.autosize.autosize
//    implementation rootProject.ext.rxjava.rxandroid
//    implementation rootProject.ext.other.util
//    implementation rootProject.ext.other.userBehavior
    implementation rootProject.ext.other.aes
    implementation rootProject.ext.other.cache

    //compose 同时支持xml和compose 自定义需求高的用xml
    api platform(rootProject.ext.compose.bom)
    api rootProject.ext.compose.compose_ui
    api rootProject.ext.compose.compose_material
    api rootProject.ext.compose.compose_runtime
    api rootProject.ext.compose.compose_activity
    debugApi rootProject.ext.compose.compose_uitooling

    //markwon AI对话专用
    api rootProject.ext.markwon.core
    api rootProject.ext.markwon.image
    api rootProject.ext.markwon.image_glide
}