plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    namespace 'io.github.kbiakov.codeview'
    compileSdk rootProject.ext.version.compileSdk
    buildFeatures.viewBinding true
    defaultConfig {
        minSdk rootProject.ext.version.minSdk
        targetSdk rootProject.ext.version.targetSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation project(':common')
}
