plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-kapt'
}

android {
    compileSdk rootProject.ext.version.compileSdk

    defaultConfig {
        minSdk rootProject.ext.version.minSdk
        targetSdk rootProject.ext.version.targetSdk

        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {

    compileOnly rootProject.ext.android.core_ktx
    compileOnly rootProject.ext.android.appcompat
    compileOnly rootProject.ext.view.constraintlayout

    //firebase core
    compileOnly platform(rootProject.ext.firebase.bom)
    compileOnly rootProject.ext.firebase.messaging
    compileOnly rootProject.ext.firebase.analytics
    compileOnly rootProject.ext.firebase.crashlytics
    implementation project(path:":sdks:util")
    implementation project(path:":sdks:cache")
//    compileOnly rootProject.ext.other.util

    implementation rootProject.ext.appsflyer.adjust
    implementation rootProject.ext.appsflyer.installreferrer

    // hilt
    compileOnly rootProject.ext.hilt.hilt_android
    kapt rootProject.ext.hilt.hilt_compiler_android
}