plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.encrypt.module'
    compileSdk rootProject.ext.version.compileSdk
    defaultConfig {
        minSdkVersion rootProject.ext.version.minSdk
        targetSdkVersion rootProject.ext.version.targetSdk

        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
    sourceSets {
        main {
            jniLibs.srcDir 'libs'
        }
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation rootProject.ext.android.core_ktx
    implementation rootProject.ext.retrofit.gson
}

apply from: "${rootProject.rootDir}/maven_push.gradle"
group = 'com.encrypt.module'
version = '1.0.0'
